# Generated by scripts/prepare_igbt_mosfet_seb_campaign.py.
# The executable per-case transient deck freezes:
#   - Load(FilePrefix="@RESTART_PREFIX@") from native device+circuit Save pair
#   - HeavyIon StartPoint=(0 3.5), Direction=(1 0), Length=50,
#     Time=1e-10, LET_f=0.1555 pC/um, Wt_hi=0.1 um
#   - separate eMobility/hMobility and all registered electrical/thermal fields
#   - 92--108 ps charge-audit snapshots
#   - an independent FinalTime=2.1e-9 segment followed immediately by
#     Plot(FilePrefix="@PREFIX@_at2p1ns" NoOverwrite)
# This tracked file is a contract; generated concrete decks are stored under
# local_runtime/tcad_projects/igbt_mosfet_seb_paper_20260714/inputs/cases/.