#!/usr/bin/env python3
"""Build the R1 thermo-coupled time series, audit sidecar, and diagnostic plots.

The input is the lossless SVisual CSV generated by extract_r1_thermal_transient.py.
No TCAD solver is invoked.  Standard library plus matplotlib are required.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "local_runtime" / "igbt_seb_thermal_runs" / (
    "A01_v2500_let15_y3p5_thermal__R1_thermo_coupled_to60__20260713T064449946Z__1d9cd23a"
)
OUTPUT_DIR = ROOT / "docs" / "changes" / "2026-07-13-igbt-seb-现有数据复盘"
ATTEMPT04 = ROOT / "local_runtime" / "igbt_seb_full_20260712_035027" / "cases" / "A01_v2500_let15_y3p5__attempt04" / "transient.csv"
COLD300 = ROOT / "local_runtime" / "igbt_seb_full_20260712_035027" / "cases" / "A01_v2500_let15_y3p5__attempt24_cold300_transient_to60" / "transient.csv"
PRESTRIKE_CUTOFF_S = 9e-11
PULSE_WINDOW_S = (9.8e-11, 1.02e-10)
PULSE_PEAK_WINDOW_S = (9e-11, 1.2e-10)
KEY_TIMES_S = (4e-10, 1e-8, 4e-8, 5e-8, 6e-8)

LONG_HEADER = [
    "sample_kind", "thermal_variant_id", "run_id", "time_s", "time_ns", "collector_inner_voltage_v",
    "ic_a_um", "tmax_k", "tpre_k", "delta_t_k", "power_w_um",
    "cumulative_port_energy_j_um", "phase", "source_file", "source_row", "diagnostic_only",
]
KEY_HEADER = [
    "sample_kind", "thermal_variant_id", "key_id", "selection_method", "target_time_s",
    "selected_time_s", "absolute_time_error_s", "ic_a_um", "tmax_k", "tpre_k", "delta_t_k",
    "power_w_um", "cumulative_port_energy_j_um", "source_path", "source_row", "diagnostic_only",
]
DERIVED_HEADER = [
    "sample_kind", "thermal_variant_id", "run_id", "segment_id", "time_s", "time_ns", "dt_s",
    "collector_inner_voltage_v", "ic_a_um", "tmax_k", "tpre_k", "delta_t_k", "power_w_um",
    "cumulative_port_energy_j_um", "d_log_ic_dt_s_inv", "d_delta_t_dt_k_s",
    "left_source_row", "left_source_time_s", "right_source_row", "right_source_time_s", "diagnostic_only",
]
COMPARISON_HEADER = [
    "target_time_s", "target_time_ns", "comparison_scope", "r1_selection_method", "r1_left_source_row",
    "r1_left_source_time_s", "r1_right_source_row", "r1_right_source_time_s", "r1_ic_a_um", "r1_tmax_k",
    "attempt04_selection_method", "attempt04_left_source_row", "attempt04_left_source_time_s", "attempt04_right_source_row",
    "attempt04_right_source_time_s", "attempt04_ic_a_um", "attempt04_tmax_k", "cold300_selection_method",
    "cold300_left_source_row", "cold300_left_source_time_s", "cold300_right_source_row", "cold300_right_source_time_s",
    "cold300_ic_a_um", "cold300_tmax_k", "r1_vs_attempt04_ic_percent_difference",
    "r1_vs_attempt04_tmax_difference_k", "r1_vs_cold300_ic_percent_difference",
    "r1_vs_cold300_tmax_difference_k", "diagnostic_only", "interpretation_boundary",
]

# The raw PLT resolves the ion pulse, whereas nanosecond-scale intervals dominate later growth.
# Each segment is a *linear* grid and derivatives never cross a segment boundary.
LINEAR_GRID_SEGMENTS = (
    ("pre_strike_0p1ps", 1e-13, 9e-11, 1e-13),
    ("ion_pulse_0p02ps", 9e-11, 1.2e-10, 2e-14),
    ("post_pulse_2ps", 1.2e-10, 4e-10, 2e-12),
    ("early_growth_0p1ns", 4e-10, 1e-8, 1e-10),
    ("late_growth_0p5ns", 1e-8, 6e-8, 5e-10),
)


def relative(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_csv(path: Path, column_names: dict[str, str]) -> list[dict[str, float | int]]:
    rows: list[dict[str, float | int]] = []
    with path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError(f"CSV without header: {path}")
        for source_row, row in enumerate(reader, start=2):
            rows.append({
                "time_s": float(row[column_names["time"]]),
                "voltage_v": float(row[column_names["voltage"]]),
                "ic_a_um": float(row[column_names["current"]]),
                "tmax_k": float(row[column_names["tmax"]]),
                "source_row": source_row,
            })
    if not rows:
        raise ValueError(f"No rows in {path}")
    return rows


def phase(time_s: float) -> str:
    if time_s <= PRESTRIKE_CUTOFF_S:
        return "pre_strike"
    if time_s <= PULSE_WINDOW_S[1]:
        return "ion_pulse"
    if time_s <= 4e-10:
        return "post_pulse_decay"
    if time_s < 1e-8:
        return "early_electrical_growth"
    if time_s < 4e-8:
        return "10_to_40ns"
    return "40_to_60ns"


def derive(raw: list[dict[str, float | int]], source: Path, variant_id: str, run_id: str) -> tuple[list[dict[str, object]], float]:
    prestrike = [row for row in raw if float(row["time_s"]) <= PRESTRIKE_CUTOFF_S]
    if not prestrike:
        raise ValueError("No stable pre-strike sample at or before 90 ps")
    # The last pre-strike PLT sample is the definition; never impose a nominal 300 K reference.
    tpre_k = float(prestrike[-1]["tmax_k"])
    energy = 0.0
    rows: list[dict[str, object]] = []
    previous: dict[str, float | int] | None = None
    for raw_row in raw:
        time_s = float(raw_row["time_s"])
        voltage_v = float(raw_row["voltage_v"])
        current_a_um = float(raw_row["ic_a_um"])
        power_w_um = abs(voltage_v * current_a_um)
        if previous is not None:
            previous_power = abs(float(previous["voltage_v"]) * float(previous["ic_a_um"]))
            energy += 0.5 * (previous_power + power_w_um) * (time_s - float(previous["time_s"]))
        rows.append({
            "sample_kind": "raw_transient",
            "thermal_variant_id": variant_id,
            "run_id": run_id,
            "time_s": time_s,
            "time_ns": time_s * 1e9,
            "collector_inner_voltage_v": voltage_v,
            "ic_a_um": current_a_um,
            "tmax_k": float(raw_row["tmax_k"]),
            "tpre_k": tpre_k,
            "delta_t_k": float(raw_row["tmax_k"]) - tpre_k,
            "power_w_um": power_w_um,
            "cumulative_port_energy_j_um": energy,
            "phase": phase(time_s),
            "source_file": relative(source),
            "source_row": raw_row["source_row"],
            "diagnostic_only": True,
        })
        previous = raw_row
    return rows, tpre_k


def closest(rows: list[dict[str, object]], target_s: float) -> dict[str, object]:
    return min(rows, key=lambda row: abs(float(row["time_s"]) - target_s))


def selected_key_row(key_id: str, target_s: float, row: dict[str, object], source: Path, method: str) -> dict[str, object]:
    selected_time = float(row["time_s"])
    return {
        "sample_kind": "key_selection",
        "thermal_variant_id": row["thermal_variant_id"],
        "key_id": key_id,
        "selection_method": method,
        "target_time_s": target_s,
        "selected_time_s": selected_time,
        "absolute_time_error_s": abs(selected_time - target_s),
        "ic_a_um": row["ic_a_um"],
        "tmax_k": row["tmax_k"],
        "tpre_k": row["tpre_k"],
        "delta_t_k": row["delta_t_k"],
        "power_w_um": row["power_w_um"],
        "cumulative_port_energy_j_um": row["cumulative_port_energy_j_um"],
        "source_path": relative(source),
        "source_row": row["source_row"],
        "diagnostic_only": True,
    }


def key_rows(rows: list[dict[str, object]], source: Path) -> list[dict[str, object]]:
    pre = [row for row in rows if float(row["time_s"]) <= PRESTRIKE_CUTOFF_S]
    pulse = [row for row in rows if PULSE_PEAK_WINDOW_S[0] <= float(row["time_s"]) <= PULSE_PEAK_WINDOW_S[1]]
    post_pulse = [row for row in rows if PULSE_WINDOW_S[1] <= float(row["time_s"]) <= 1e-9]
    if not pre or not pulse or not post_pulse:
        raise ValueError("Required pre-strike, ion-pulse, or post-pulse samples are missing")
    pre_last = pre[-1]
    pulse_peak = max(pulse, key=lambda row: abs(float(row["ic_a_um"])))
    post_min = min(post_pulse, key=lambda row: abs(float(row["ic_a_um"])))
    events: list[tuple[str, float, dict[str, object]]] = [
        ("pre_strike_last", float(pre_last["time_s"]), pre_last),
        ("pulse_peak_near_100ps", 1e-10, pulse_peak),
        ("post_pulse_sample_min", float(post_min["time_s"]), post_min),
    ]
    events.extend((f"time_{target * 1e9:g}ns", target, closest(rows, target)) for target in KEY_TIMES_S)
    return [
        selected_key_row(
            key_id, target, row, source,
            "raw_exact" if float(row["time_s"]) == target else "raw_nearest",
        )
        for key_id, target, row in events
    ]


def bracket(rows: list[dict[str, object]], target_s: float) -> tuple[dict[str, object], dict[str, object]]:
    first_time = float(rows[0]["time_s"]); last_time = float(rows[-1]["time_s"])
    tolerance = max(1e-22, abs(target_s) * 1e-12)
    if abs(target_s - first_time) <= tolerance:
        target_s = first_time
    elif abs(target_s - last_time) <= tolerance:
        target_s = last_time
    if target_s < first_time or target_s > last_time:
        raise ValueError(f"Target {target_s:g} s lies outside source range")
    for row in rows:
        if abs(float(row["time_s"]) - target_s) <= tolerance:
            return row, row
    for left, right in zip(rows, rows[1:]):
        if float(left["time_s"]) < target_s < float(right["time_s"]):
            return left, right
    raise ValueError(f"Could not bracket target {target_s:g} s")


def linear_interpolated(rows: list[dict[str, object]], target_s: float) -> dict[str, object]:
    left, right = bracket(rows, target_s)
    left_time = float(left["time_s"]); right_time = float(right["time_s"])
    fraction = 0.0 if left_time == right_time else (target_s - left_time) / (right_time - left_time)
    def value(name: str) -> float:
        return float(left[name]) + fraction * (float(right[name]) - float(left[name]))
    return {
        "selection_method": "raw_exact" if left_time == right_time else "linear_interpolation",
        "target_time_s": target_s,
        "collector_inner_voltage_v": value("collector_inner_voltage_v"),
        "ic_a_um": value("ic_a_um"),
        "tmax_k": value("tmax_k"),
        "tpre_k": value("tpre_k"),
        "delta_t_k": value("delta_t_k"),
        "power_w_um": value("power_w_um"),
        "cumulative_port_energy_j_um": value("cumulative_port_energy_j_um"),
        "left_source_row": left["source_row"],
        "left_source_time_s": left_time,
        "right_source_row": right["source_row"],
        "right_source_time_s": right_time,
    }


def linear_grid(rows: list[dict[str, object]], tpre_k: float) -> list[dict[str, object]]:
    output: list[dict[str, object]] = []
    energy_offset = 0.0
    for segment_id, start_s, end_s, dt_s in LINEAR_GRID_SEGMENTS:
        count = round((end_s - start_s) / dt_s)
        if not math.isclose(start_s + count * dt_s, end_s, rel_tol=0.0, abs_tol=1e-22):
            raise ValueError(f"Linear grid does not close: {segment_id}")
        segment: list[dict[str, object]] = []
        for index in range(count + 1):
            target_s = start_s + index * dt_s
            point = linear_interpolated(rows, target_s)
            point.update({
                "sample_kind": "derived_linear_grid",
                "thermal_variant_id": rows[0]["thermal_variant_id"],
                "run_id": rows[0]["run_id"],
                "segment_id": segment_id,
                "time_s": target_s,
                "time_ns": target_s * 1e9,
                "dt_s": dt_s if index else 0.0,
                "delta_t_k": float(point["tmax_k"]) - tpre_k,
                "diagnostic_only": True,
            })
            segment.append(point)
        for index, point in enumerate(segment):
            if index:
                previous = segment[index - 1]
                energy_offset += 0.5 * (float(previous["power_w_um"]) + float(point["power_w_um"])) * dt_s
            point["cumulative_port_energy_j_um"] = energy_offset
            if index == 0 or index == len(segment) - 1:
                point["d_log_ic_dt_s_inv"] = "NA"
                point["d_delta_t_dt_k_s"] = "NA"
            else:
                previous = segment[index - 1]; following = segment[index + 1]
                point["d_log_ic_dt_s_inv"] = (math.log(abs(float(following["ic_a_um"]))) - math.log(abs(float(previous["ic_a_um"])))) / (2 * dt_s)
                point["d_delta_t_dt_k_s"] = (float(following["delta_t_k"]) - float(previous["delta_t_k"])) / (2 * dt_s)
        output.extend(segment)
    return output


def common_time_comparison(r1: list[dict[str, object]], attempt04: list[dict[str, object]], cold300: list[dict[str, object]]) -> list[dict[str, object]]:
    output = []
    for target_s in (1e-8, 4e-8, 5e-8, 6e-8):
        selected = [linear_interpolated(series, target_s) for series in (r1, attempt04, cold300)]
        r1_point, attempt04_point, cold300_point = selected
        row: dict[str, object] = {
            "target_time_s": target_s,
            "target_time_ns": target_s * 1e9,
            "comparison_scope": "common-target linear interpolation from raw transient samples; not raw simultaneous samples",
            "diagnostic_only": True,
            "interpretation_boundary": "MESH_SENSITIVE; A01 INDETERMINATE; no thermal-causality or SEB conclusion.",
        }
        for prefix, point in zip(("r1", "attempt04", "cold300"), selected):
            for name in ("selection_method", "left_source_row", "left_source_time_s", "right_source_row", "right_source_time_s", "ic_a_um", "tmax_k"):
                row[f"{prefix}_{name}"] = point[name]
        row["r1_vs_attempt04_ic_percent_difference"] = 100 * (float(r1_point["ic_a_um"]) / float(attempt04_point["ic_a_um"]) - 1)
        row["r1_vs_attempt04_tmax_difference_k"] = float(r1_point["tmax_k"]) - float(attempt04_point["tmax_k"])
        row["r1_vs_cold300_ic_percent_difference"] = 100 * (float(r1_point["ic_a_um"]) / float(cold300_point["ic_a_um"]) - 1)
        row["r1_vs_cold300_tmax_difference_k"] = float(r1_point["tmax_k"]) - float(cold300_point["tmax_k"])
        output.append(row)
    return output


def write_csv(path: Path, header: list[str], rows: Iterable[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=header, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def manifest_artifact(manifest: dict[str, object], relative_path: str) -> dict[str, object]:
    return next(item for item in manifest["artifacts"] if item["relative_path"] == relative_path)  # type: ignore[index]


def verify_manifest_hashes(manifest: dict[str, object]) -> list[dict[str, object]]:
    required_artifacts = (
        "artifacts/transient_r1_coupled.plt", "artifacts/field_pre_des.tdr", "artifacts/field_0p4ns_des.tdr",
        "artifacts/field_10ns_des.tdr", "artifacts/field_40ns_des.tdr", "artifacts/field_50ns_des.tdr",
        "artifacts/field_60ns_des.tdr", "artifacts/checkpoint_60ns_des.sav",
    )
    entries = list(manifest["inputs"]) + [manifest_artifact(manifest, name) for name in required_artifacts]  # type: ignore[arg-type,index]
    checks = []
    for entry in entries:
        path = RUN_DIR / str(entry["relative_path"])
        actual = sha256(path)
        checks.append({"relative_path": entry["relative_path"], "expected_sha256": entry["sha256"], "actual_sha256": actual, "match": actual == entry["sha256"]})
    if not all(bool(item["match"]) for item in checks):
        raise ValueError("Manifest SHA-256 mismatch")
    return checks


def build_sidecar(
    manifest: dict[str, object], rows: list[dict[str, object]], tpre_k: float,
    key_data: list[dict[str, object]], derived_grid: list[dict[str, object]],
) -> dict[str, object]:
    artifacts = {
        name: manifest_artifact(manifest, name)
        for name in (
            "artifacts/transient_r1_coupled.plt", "artifacts/field_pre_des.tdr", "artifacts/field_0p4ns_des.tdr",
            "artifacts/field_10ns_des.tdr", "artifacts/field_40ns_des.tdr", "artifacts/field_50ns_des.tdr",
            "artifacts/field_60ns_des.tdr", "artifacts/checkpoint_60ns_des.sav",
        )
    }
    raw_source = RUN_DIR / "postprocess" / "r1_transient_raw.csv"
    deck = next(item for item in manifest["inputs"] if item["relative_path"] == "inputs/r1_thermo_coupled_to60.cmd")  # type: ignore[index]
    mesh = next(item for item in manifest["inputs"] if item["relative_path"] == "inputs/igbt_seb_msh.tdr")  # type: ignore[index]
    restart = [item for item in manifest["inputs"] if str(item["relative_path"]).startswith("inputs/r1_bias2500")]  # type: ignore[index]
    return {
        "schema_version": "igbt_seb_thermal_sidecar/v1",
        "thermal_variant_id": "R1_THERMO_COUPLED_TCONT300",
        "run_id": manifest["run_id"],
        "parent_dc_run_id": manifest["parent_run_id"],
        "case_id": manifest["case_id"],
        "attempt_id": manifest["attempt_id"],
        "model_declaration": {
            "thermal_mode": "Thermodynamic; Poisson/Electron/Hole/Temperature coupled in every transient solve",
            "thermode_contacts": {"Gate": 300, "Emitter": 300, "Collector": 300},
            "temperature_initialization_k": 300,
            "heavy_ion": "LET=15 MeV cm^2 mg^-1; 0.1555 pC/um; y=3.5 um; 50 um; Wt_hi=0.1 um",
            "port_power_definition": "abs(Collector InnerVoltage * Collector TotalCurrent)",
            "energy_definition": "trapezoidal integral of the absolute port power over PLT sample times",
        },
        "tpre": {
            "value_k": tpre_k,
            "definition": "Tmax at the last pre-strike PLT sample at or before 90 ps; not a fixed 300 K subtraction",
            "source_time_s": max(float(row["time_s"]) for row in rows if float(row["time_s"]) <= PRESTRIKE_CUTOFF_S),
        },
        "time_series": rows,
        "key_times": key_data,
        "derived_linear_grid": {
            "path": "docs/changes/2026-07-13-igbt-seb-现有数据复盘/data/r1_thermal_linear_grid_derived.csv",
            "sample_kind": "derived_linear_grid",
            "point_count": len(derived_grid),
            "segments": [
                {"segment_id": segment_id, "start_s": start_s, "end_s": end_s, "dt_s": dt_s}
                for segment_id, start_s, end_s, dt_s in LINEAR_GRID_SEGMENTS
            ],
            "interpolation": "piecewise-linear from raw PLT samples; derivatives use central differences within each uniform linear segment only",
            "boundary_derivatives": "NA; derivatives do not cross segment boundaries",
        },
        "field_completeness": {
            "plt_variables_used": ["time", "Collector InnerVoltage", "Collector TotalCurrent", "Tmax"],
            "field_tdrs_present": ["pre", "0.4 ns", "10 ns", "40 ns", "50 ns", "60 ns"],
            "tdr_fields_declared_by_deck": ["LatticeTemperature", "ElectricField", "TotalCurrent", "JouleHeat", "TotalHeat", "HeavyIonGeneration", "AvalancheGeneration", "Potential", "SpaceCharge"],
            "checkpoint_60ns_present": True,
            "required_artifacts": artifacts,
            "raw_extraction": {
                "path": relative(raw_source),
                "sha256": sha256(raw_source),
                "sample_count": len(rows),
                "method": "SVisual Python API with --threads 1; no resampling",
            },
        },
        "provenance": {"manifest": relative(RUN_DIR / "run_manifest.json"), "deck": deck, "mesh": mesh, "restart_saves": restart},
        "stop_reason": "scheduled transient end at 60 ns; no BreakCriteria trip recorded",
        "lifecycle": manifest["lifecycle"],
        "exit_code": int(manifest["exit_code"]),
        "wall_time_seconds": int(manifest["wall_time_seconds"]),
        "diagnostic_only": True,
        "interpretation_boundary": "MESH_SENSITIVE. This sidecar reports temporal covariation only; it neither establishes thermal causality nor passes R2/R3 intervention gates.",
    }


def save_figure(figure: plt.Figure, png: Path) -> None:
    png.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(png, dpi=300, bbox_inches="tight")
    figure.savefig(png.with_suffix(".svg"), bbox_inches="tight")
    plt.close(figure)


def plot_r1_diagnostic(rows: list[dict[str, object]], output: Path) -> None:
    figure, ax_i = plt.subplots(figsize=(10.5, 6.7))
    ax_t = ax_i.twinx()
    times = [float(row["time_s"]) for row in rows]
    currents = [abs(float(row["ic_a_um"])) for row in rows]
    positive_temperature = [row for row in rows if float(row["delta_t_k"]) > 0]
    ax_i.plot(times, currents, color="#1b1b1b", marker="o", markersize=2.8, linewidth=1.45, label="Ic")
    ax_t.plot([float(row["time_s"]) for row in positive_temperature], [float(row["delta_t_k"]) for row in positive_temperature], color="#c75520", linestyle="--", marker="^", markersize=3.0, linewidth=1.35, label="ΔT")
    ax_i.set_xscale("log"); ax_i.set_yscale("log"); ax_t.set_yscale("log")
    ax_i.set_xlabel("Time (s)"); ax_i.set_ylabel("Collector current |Ic| (A/µm)"); ax_t.set_ylabel("ΔT = Tmax − Tpre (K)")
    ax_i.axvline(1e-10, color="#666666", linestyle=":", linewidth=1.0)
    ax_i.text(1e-10, min(currents) * 2, "ion strike\n100 ps", ha="center", fontsize=8.5)
    ax_i.grid(True, which="both", linestyle=":", alpha=0.35)
    ax_i.legend(handles=[Line2D([0], [0], color="#1b1b1b", marker="o", label="Ic"), Line2D([0], [0], color="#c75520", linestyle="--", marker="^", label="ΔT")], loc="upper left")
    ax_i.set_title("R1 fully thermo-coupled timing diagnostic\n2500 V; LET 15 MeV·cm²·mg⁻¹; temporal covariation only")
    figure.text(0.5, 0.01, "Diagnostic-only; MESH_SENSITIVE. The plot does not establish thermal causality.", ha="center", fontsize=8.5)
    figure.tight_layout(rect=(0.02, 0.045, 0.98, 0.98))
    save_figure(figure, output)


def plot_r1_tmax(rows: list[dict[str, object]], output: Path) -> None:
    figure, axis = plt.subplots(figsize=(9.7, 5.4))
    axis.plot([float(row["time_s"]) for row in rows], [float(row["tmax_k"]) for row in rows], color="#c75520", linewidth=1.6, marker="o", markersize=2.8)
    axis.set_xscale("log"); axis.set_xlabel("Time (s)"); axis.set_ylabel("Tmax (K), linear axis")
    axis.set_title("R1 Tmax companion view\n2500 V; LET 15 MeV·cm²·mg⁻¹")
    axis.grid(True, which="both", linestyle=":", alpha=0.35)
    figure.text(0.5, 0.01, "Diagnostic-only; MESH_SENSITIVE. Absolute temperature is timing context, not a causal claim.", ha="center", fontsize=8.5)
    figure.tight_layout(rect=(0.02, 0.04, 0.98, 0.98))
    save_figure(figure, output)


def plot_comparison(r1: list[dict[str, object]], attempt04: list[dict[str, object]], cold300: list[dict[str, object]], output: Path) -> None:
    figure, (ax_i, ax_t) = plt.subplots(2, 1, figsize=(10.5, 8.1), sharex=True)
    datasets = [
        ("R1 thermo-coupled (new)", r1, "#111111"),
        ("attempt04 thermo-coupled (existing)", attempt04, "#0072B2"),
        ("cold300 (existing cold initial state)", cold300, "#d55e00"),
    ]
    for label, rows, color in datasets:
        window = [row for row in rows if float(row["time_s"]) <= 6e-8]
        ax_i.plot([float(row["time_s"]) for row in window], [abs(float(row["ic_a_um"])) for row in window], label=label, color=color, linewidth=1.35)
        ax_t.plot([float(row["time_s"]) for row in window], [float(row["tmax_k"]) for row in window], label=label, color=color, linewidth=1.35)
    for axis in (ax_i, ax_t):
        axis.set_xscale("log"); axis.grid(True, which="both", linestyle=":", alpha=0.35); axis.legend(fontsize=8.3)
    ax_i.set_yscale("log"); ax_i.set_ylabel("|Ic| (A/µm)"); ax_t.set_ylabel("Tmax (K)"); ax_t.set_xlabel("Time (s)")
    ax_i.set_title("Comparable 2500 V / LET 15 timing traces\nR1 and existing attempts are not different-bias experiments")
    figure.text(0.5, 0.01, "Diagnostic-only; MESH_SENSITIVE. Comparative timing context only; no thermal causality or SEB classification is inferred.", ha="center", fontsize=8.5)
    figure.tight_layout(rect=(0.02, 0.04, 0.98, 0.98))
    save_figure(figure, output)


def validate(rows: list[dict[str, object]], keys: list[dict[str, object]], grid: list[dict[str, object]], manifest: dict[str, object]) -> None:
    if len(rows) != 158:
        raise ValueError(f"Unexpected R1 point count: {len(rows)}")
    if any(row["sample_kind"] != "raw_transient" for row in rows):
        raise ValueError("Raw R1 rows lost sample-kind provenance")
    if abs(float(rows[-1]["time_s"]) - 6e-8) > 1e-19:
        raise ValueError("R1 did not end at 60 ns")
    if abs(float(rows[17]["tpre_k"]) - 324.633215689) > 1e-9:
        raise ValueError("Unexpected last pre-strike Tmax")
    expected_keys = {
        "pre_strike_last", "pulse_peak_near_100ps", "post_pulse_sample_min", "time_0.4ns",
        "time_10ns", "time_40ns", "time_50ns", "time_60ns",
    }
    if {row["key_id"] for row in keys} != expected_keys:
        raise ValueError("Key-time set changed")
    if any(row["selection_method"] not in {"raw_exact", "raw_nearest"} for row in keys):
        raise ValueError("Invalid raw key selection method")
    expected_grid_points = sum(round((end_s - start_s) / dt_s) + 1 for _, start_s, end_s, dt_s in LINEAR_GRID_SEGMENTS)
    if len(grid) != expected_grid_points or any(row["sample_kind"] != "derived_linear_grid" for row in grid):
        raise ValueError("Derived linear grid schema/count changed")
    if manifest["lifecycle"] != "SUCCEEDED" or str(manifest["exit_code"]) != "0":
        raise ValueError("R1 manifest did not record success")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, default=RUN_DIR)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    global RUN_DIR
    RUN_DIR = args.run_dir.resolve()
    raw_path = RUN_DIR / "postprocess" / "r1_transient_raw.csv"
    manifest_path = RUN_DIR / "run_manifest.json"
    raw = read_csv(raw_path, {"time": "time_s", "voltage": "collector_inner_voltage_v", "current": "collector_total_current_a_um", "tmax": "tmax_k"})
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    hash_checks = verify_manifest_hashes(manifest)
    r1, tpre_k = derive(raw, raw_path, "R1_THERMO_COUPLED_TCONT300", str(manifest["run_id"]))
    keys = key_rows(r1, raw_path)
    grid = linear_grid(r1, tpre_k)
    validate(r1, keys, grid, manifest)

    data_dir = args.output_dir / "data"; figures_dir = args.output_dir / "figures"
    write_csv(data_dir / "r1_thermal_transient_long.csv", LONG_HEADER, r1)
    write_csv(data_dir / "r1_thermal_key_points.csv", KEY_HEADER, keys)
    (data_dir / "r1_thermal_key_points.json").write_text(
        json.dumps({
            "schema_version": "igbt_seb_r1_key_points/v1",
            "source_kind": "raw_transient",
            "source_path": relative(raw_path),
            "selection_rule": "Each key point is a retained raw PLT sample. raw_nearest is used only for the approximately 100 ps peak; no key point is interpolated.",
            "rows": keys,
        }, indent=2), encoding="utf-8",
    )
    write_csv(data_dir / "r1_thermal_linear_grid_derived.csv", DERIVED_HEADER, grid)
    sidecar = build_sidecar(manifest, r1, tpre_k, keys, grid)
    (data_dir / "r1_thermal_sidecar.json").write_text(json.dumps(sidecar, indent=2), encoding="utf-8")
    audit = {
        "run_id": manifest["run_id"], "manifest_path": relative(manifest_path), "lifecycle": manifest["lifecycle"],
        "exit_code": int(manifest["exit_code"]), "wall_time_seconds": int(manifest["wall_time_seconds"]),
        "input_sha256": {item["relative_path"]: item["sha256"] for item in manifest["inputs"]},
        "hash_verification": hash_checks,
        "required_artifacts": sidecar["field_completeness"]["required_artifacts"],
        "plt_fields": json.loads((RUN_DIR / "postprocess" / "r1_transient_extract_metadata.json").read_text(encoding="utf-8")),
        "audit_result": "PASS: manifest, success exit, input provenance, 60 ns Save/checkpoint, PLT fields, and pre/0.4/10/40/50/60 ns field TDRs are present.",
    }
    (data_dir / "r1_thermal_archive_audit.json").write_text(json.dumps(audit, indent=2), encoding="utf-8")

    plot_r1_diagnostic(r1, figures_dir / "r1_thermal_timing_diagnostic.png")
    plot_r1_tmax(r1, figures_dir / "r1_thermal_tmax_linear.png")
    existing = read_csv(ATTEMPT04, {"time": "time_s", "voltage": "collector_inner_v", "current": "collector_current_a_um", "tmax": "tmax_k"})
    cold = read_csv(COLD300, {"time": "time_s", "voltage": "vce_v", "current": "ic_a_um", "tmax": "tmax_k"})
    existing_rows, _ = derive(existing, ATTEMPT04, "ATTEMPT04_THERMO_COUPLED", "A01_v2500_let15_y3p5__attempt04")
    cold_rows, _ = derive(cold, COLD300, "ATTEMPT24_COLD300", "A01_v2500_let15_y3p5__attempt24_cold300_transient_to60")
    comparison = common_time_comparison(r1, existing_rows, cold_rows)
    write_csv(data_dir / "r1_vs_attempt04_cold300_common_times.csv", COMPARISON_HEADER, comparison)
    (data_dir / "r1_vs_attempt04_cold300_common_times.json").write_text(
        json.dumps({
            "schema_version": "igbt_seb_common_time_comparison/v1",
            "series": ["R1_THERMO_COUPLED_TCONT300", "ATTEMPT04_THERMO_COUPLED", "ATTEMPT24_COLD300"],
            "method": "Each series is linearly interpolated from bracketing raw transient samples at common target times; no interpolated value is labeled raw.",
            "comparison_scope": "diagnostic_only; MESH_SENSITIVE; A01 INDETERMINATE; not a thermal-causality intervention result.",
            "rows": comparison,
        }, indent=2), encoding="utf-8",
    )
    plot_comparison(r1, existing_rows, cold_rows, figures_dir / "r1_vs_attempt04_cold300_timing.png")

    print(json.dumps({"r1_points": len(r1), "tpre_k": tpre_k, "key_points": keys, "data_dir": str(data_dir), "figures_dir": str(figures_dir)}, indent=2))


if __name__ == "__main__":
    main()